// Objective-C API for talking to github.com/ichibankunio/shader_uniform_test/mobile Go package.
//   gobind -lang=objc github.com/ichibankunio/shader_uniform_test/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Dummy is a dummy exported function.

gomobile doesn't compile a package that doesn't include any exported function.
Dummy forces gomobile to compile this package.
 */
FOUNDATION_EXPORT void MobileDummy(void);

#endif
