
// Objective-C API for talking to the following Go packages
//
//	github.com/ichibankunio/shader_uniform_test/mobile
//	github.com/hajimehoshi/ebiten/v2/mobile/ebitenmobileview
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_FRAMEWORK_H__
#define __Mobile_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Ebitenmobileview.objc.h"
#include "Universe.objc.h"

#endif
